---

# General setup

# Basic configuration to guard against double-pipelines
workflow:
  rules:
    # This workflow entry allows pipelines for schedules events in which case it checks the
    # TZ_SCHEDULE_KIND which must be set in the pipeline scheduling interface
    # In either case it sets the TZ_PIPELINE_KIND variable to allow jobs to
    # selectively run on some pipelines but not all.
    # See https://docs.gitlab.com/ee/ci/yaml/README.html#workflow for additional
    # details.
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $TZ_SCHEDULE_KIND == "EXTENDED_TESTS"'
      variables:
        TZ_PIPELINE_KIND: "SCHEDULE"
      when: always
    # Switch between branch pipelines and merge request pipelines.
    # https://docs.gitlab.com/13.12/ee/ci/yaml/README.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # This workflow entry allows pipelines for push events (including force-push, push of fixup commits, rebase, etc.)
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never # default

# The "manual" stage exists to fix a UI problem that occurs when mixing
# manual and non-manual jobs.
stages:
  - bootstrap
  - sanity
  - build
  - test
  - doc
  - packaging
  - build_release
  - publish_release
  - test_coverage
  - manual

include:
  - .gitlab/ci/templates.yml

# Actual jobs are defined in these included files

  - .gitlab/ci/bootstrap-opam-pipeline.yml
  - .gitlab/ci/sanity.yml
  - .gitlab/ci/build.yml
  - .gitlab/ci/lints.yml
  - .gitlab/ci/unittest.yml
  - .gitlab/ci/integration.yml
  - .gitlab/ci/liquidity-baking-scripts-integrity.yml
  - .gitlab/ci/coq.yml
  - .gitlab/ci/tezt.yml
  - .gitlab/ci/doc.yml
  - .gitlab/ci/publish.yml
  - .gitlab/ci/coverage.yml
  - .gitlab/ci/test-doc-scripts.yml
