# SPDX-FileCopyrightText: 2023 TriliTech <contact@trili.tech>
#
# SPDX-License-Identifier: MIT

[package]
name = "installer-kernel"
version = "0.1.0"
edition = "2021"
authors = ["TriliTech <contact@trili.tech>"]

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["std"]
std = []
entrypoint = []

[dependencies.blst]
version = "0.3.10"
features = ["portable"]

[dependencies.tezos-smart-rollup]
path = "../sdk"
version = "0.1.0"
default-features = false

[dependencies.tezos-smart-rollup-installer-config]
path = "../installer-config"
default-features = false
