---

.build_template:
  extends:
    - .default_settings_template
    - .image_template__runtime_build_test_dependencies_template
  stage: build
  before_script:
    - . ./scripts/version.sh
    # Load the environment poetry previously created in the docker image.
    # Give access to the Python dependencies/executables
    - . $HOME/.venv/bin/activate

.build:
  extends: .build_template
  needs: []
  variables:
    ARCH: ""
  script:
    # We remove protocols not needed for tests in order to speed up the CI.
    - ./scripts/remove-old-protocols.sh
    - . ./scripts/version.sh
    # 1. Some basic, fast sanity checks
    - if [ "${build_deps_image_version}" != "${opam_repository_tag}" ] ; then
        echo "Inconsistent dependencies hash between 'scripts/version.sh' and '.gitlab-ci.yml'." ;
        echo "${build_deps_image_version} != ${opam_repository_tag}" ;
        exit 1 ;
      fi
    - diff tests_python/poetry.lock /home/tezos/poetry.lock
    - diff tests_python/pyproject.toml /home/tezos/pyproject.toml
    - dune build @runtest_dune_template
    # 2. Actually build
    - make all build-test
    # 3. clean-up caches before uploading the cache
    - opam clean
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _build
      - tezos-*
  artifacts:
    name: "build-$ARCH-$CI_COMMIT_REF_SLUG"
    paths:
      - tezos-*
      - src/proto_*/parameters/*.json
      - _build/default/src/lib_protocol_compiler/main_native.exe
    expire_in: 1 day
    when: on_success

build_arm64:
  extends:
    - .build
    - .rules_template__development_arm64
  variables:
    ARCH: "arm64"
  tags:
    - arm64

build_x86_64:
  extends:
    - .build
    - .rules_template__development
  variables:
    ARCH: "x86_64"
